language: php

php:
    - "7.4"

before_script:
    - composer update
    - composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
    - composer install --prefer-source --no-interaction --dev

script: ./vendor/bin/phpunit tests

notifications:
    on_success: always
    on_failure: always
