language: php

php:
    - "8.0"

before_script:
    - composer update --ignore-platform-reqs
    - composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
    - composer install --prefer-source --no-interaction --ignore-platform-reqs

script: ./vendor/bin/phpunit tests

notifications:
    on_success: always
    on_failure: always
