language: php

php:
    - "7.4"

before_script:
    - composer update
    - composer install --prefer-source --no-interaction --dev

script: phpunit

notifications:
    on_success: always
    on_failure: always
